export const userRows = [
    {
        id: 1,
        username: "Ben stock",
        img: "https://images.unsplash.com/photo-1583864697784-a0efc8379f70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxMjA3fDB8MXxzZWFyY2h8Mnx8YSUyMG1hbnx8MHx8fHwxNjI1ODI5NTEz&ixlib=rb-1.2.1&q=80&w=1080",
        status: "Active",
        email: "benstock23@gmail.com",
        age: 34,
    },
    {
        id: 2,
        username: "jamia millia islamia",
        img: "https://images.indianexpress.com/2023/06/Jamia-Millia-Islamia-1.jpg",
        status: "Passive",
        email: "2jamia@gmail.com",
        age: 42,
    },
    {
        id: 3,
        username: "Rohit",
        img: "https://tse1.mm.bing.net/th?id=OIP.jlgnoZGyiO9Xz1Oheb4INgHaE8&pid=Api&P=0&h=220",
        status: "Pending",
        email: "3lannister@gmail.com",
        age: 30,
    },
    {
        id: 4,
        username: "Kiven",
        img: "https://tse2.mm.bing.net/th?id=OIP.9OblCAWmhVxv6IoDcS-O6wHaNK&pid=Api&P=0&h=220",
        status: "Active",
        email: "kivenjam143@gmail.com",
        age: 31,
    },
    {
        id: 4,
        username: "Yone",
        img: "https://tse3.mm.bing.net/th?id=OIP.IJ4dLqLLA-_uv05k9so9EQHaHa&pid=Api&P=0&h=220",
        status: "Pending",
        email: "yonesow21@gmail.com",
        age: 31,
    },
    {
        id: 5,
        username: "Frank",
        img: "https://tse4.mm.bing.net/th?id=OIP.SYEZogSgRAcR1FuVB5s82QHaLH&pid=Api&P=0&h=220",
        status: "Active",
        email: "frankjo54@gmail.com",
        age: 31,
    },
    {
        id: 6,
        username: "John",
        img: "https://trendheads.nl/wp-content/uploads/2017/04/opscheer-herenkapsel-001.jpg",
        status: "Active",
        email: "2jam@gmail.com",
        age: 20,
    },
    {
        id: 7,
        username: "Roye",
        img: "",
        status: "Pending",
        email: "1roxie@gmail.com",
        age: 41,
    },
]