export const userRows = [
    {
        id: 1,
        username: "Acer Nitro 5",
        img: "https://m.media-amazon.com/images/I/81bc8mA3nKL._AC_UY327_FMwebp_QL65_.jpg",
        status: "Instock",
        amount: "785",
        quantity: 3,
    },
    {
        id: 2,
        username: "Playstation 6",
        img: "https://m.media-amazon.com/images/I/31JaiPXYI8L._AC_UY327_FMwebp_QL65_.jpg",
        status: "Outstock",
        amount: "900",
        quantity: 0,
    },
    {
        id: 3,
        username: "Redragon S101",
        img: "https://m.media-amazon.com/images/I/71kr3WAj1FL._AC_UY327_FMwebp_QL65_.jpg",
        status: "Onway",
        amount: "35",
        quantity: 3,
    },
    {
        id: 4,
        username: "ASUS ROG Strix",
        img: "https://m.media-amazon.com/images/I/81hH5vK-MCL._AC_UY327_FMwebp_QL65_.jpg",
        status: "Instock",
        amount: "2000",
        quantity: 1,
    },
    {
        id: 4,
        username: "Razer Blade 15",
        img: "https://m.media-amazon.com/images/I/71wF7YDIQkL._AC_UY327_FMwebp_QL65_.jpg",
        status: "Onway",
        amount: "920",
        quantity: 10,
    },
    {
        id: 5,
        username: "HP Laptop i5",
        img: "https://www.startech.com.bd/image/cache/catalog/laptop/hp-laptop/pavilion-15/pavilion-15-1-500x500.jpg",
        status: "Instock",
        amount: "65000",
        quantity: 3,
    },
    {
        id: 6,
        username: "HP Moniter",
        img: "https://tse3.mm.bing.net/th?id=OIP.jdqBeVzJeGzfu4upfDbFTgHaFj&pid=Api&P=0&h=220",
        status: "Instock",
        amount: "10000",
        quantity: 2,
    },
    {
        id: 7,
        username: "Head Phone",
        img: "https://www.binarytides.com/blog/wp-content/uploads/2020/02/oneodio-wired-gaming-stereo-headsets-957x1024.jpg",
        status: "Onway",
        amount: "300",
        quantity: 40,
    },
]